# config/config.yaml
dev:
  warehouse: DEV_WH
  database: DEV_DB
  schema: PUBLIC

stg:
  warehouse: STG_WH
  database: STG_DB
  schema: PUBLIC

prd:
  warehouse: PROD_WH
  database: PROD_DB
  schema: PUBLIC
